# Hosts beschreiben die Hardware-Knoten. 

# The hosts will have virtual mac addresses because ovs will claim the network device. 
# The virtual MAC is used as soon the device is UP. 
# The physical MAC address is used during bootstrapping. 
# If no virtual MAC is set or the phys-macaddress is the same as macaddress, no OVS should be used. 

host:
  - name: clt-lab-n-1160 # name for bootstrapping
    macaddress: 00-16-3E-6D-CF-1B
    phys-macaddress: 1C-69-7A-63-BB-20
  - name: clt-lab-n-1161
    macaddress: 00-16-3E-7C-01-EF
    phys-macaddress: 1C-69-7A-63-B0-D3
  - name: clt-lab-n-1162
    macaddress: 00-16-3E-32-3B-27
    phys-macaddress: 1C-69-7A-63-A0-D9